# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        args: ["--max-line-length", "99"]
        language: python
        types: [python]
        require_serial: true
    -   id: black
        name: black
        entry: black
        language: python
        types_or: [python, pyi]
        require_serial: true
    -   id: mypy
        name: mypy
        entry: mypy
        args: ["--show-error-codes"]
        language: python
        types_or: [python, pyi]
        require_serial: true
    -   id: isort
        name: isort
        entry: isort
        language: python
        types_or: [cython, python, pyi]
        args: ['--filter-files']
        require_serial: true
