# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: python
        types_or: [python, pyi]
        require_serial: true
    -   id: ruff
        name: ruff
        entry: ruff
        language: system
        types_or: [python, pyi]
        args: ["--fix", "--exit-non-zero-on-fix"]
    -   id: mypy
        name: mypy
        entry: mypy
        language: python
        types_or: [python, pyi]
        require_serial: true
        pass_filenames: false
